# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwin.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QMainWindow, QMenuBar, QProgressBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(928, 403)
        MainWindow.setIconSize(QSize(20, 20))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.startbut = QPushButton(self.centralwidget)
        self.startbut.setObjectName(u"startbut")
        self.startbut.setGeometry(QRect(730, 310, 151, 41))
        font = QFont()
        font.setFamilies([u"Microsoft YaHei UI"])
        font.setPointSize(12)
        font.setBold(True)
        self.startbut.setFont(font)
        self.startbut.setStyleSheet(u"")
        self.startbut.setFlat(False)
        self.select_inputpath = QPushButton(self.centralwidget)
        self.select_inputpath.setObjectName(u"select_inputpath")
        self.select_inputpath.setGeometry(QRect(17, 13, 111, 31))
        font1 = QFont()
        font1.setBold(True)
        self.select_inputpath.setFont(font1)
        self.select_savepath = QPushButton(self.centralwidget)
        self.select_savepath.setObjectName(u"select_savepath")
        self.select_savepath.setGeometry(QRect(420, 15, 111, 31))
        self.select_savepath.setFont(font1)
        self.inputpath_2 = QLabel(self.centralwidget)
        self.inputpath_2.setObjectName(u"inputpath_2")
        self.inputpath_2.setGeometry(QRect(137, 23, 271, 16))
        font2 = QFont()
        font2.setItalic(False)
        self.inputpath_2.setFont(font2)
        self.savepath = QLabel(self.centralwidget)
        self.savepath.setObjectName(u"savepath")
        self.savepath.setGeometry(QRect(550, 25, 311, 16))
        self.savepath.setFont(font2)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 111, 16))
        font3 = QFont()
        font3.setUnderline(False)
        self.label.setFont(font3)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(431, 101, 71, 16))
        font4 = QFont()
        font4.setPointSize(9)
        self.label_2.setFont(font4)
        self.origin_lang = QComboBox(self.centralwidget)
        self.origin_lang.addItem("")
        self.origin_lang.addItem("")
        self.origin_lang.setObjectName(u"origin_lang")
        self.origin_lang.setGeometry(QRect(130, 90, 69, 22))
        self.target_lang = QComboBox(self.centralwidget)
        self.target_lang.addItem("")
        self.target_lang.setObjectName(u"target_lang")
        self.target_lang.setGeometry(QRect(510, 100, 69, 22))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(610, 102, 41, 16))
        self.role1 = QComboBox(self.centralwidget)
        self.role1.addItem("")
        self.role1.addItem("")
        self.role1.addItem("")
        self.role1.addItem("")
        self.role1.setObjectName(u"role1")
        self.role1.setGeometry(QRect(660, 100, 151, 22))
        self.preview_role = QPushButton(self.centralwidget)
        self.preview_role.setObjectName(u"preview_role")
        self.preview_role.setGeometry(QRect(820, 99, 75, 24))
        self.translate_process_bar = QProgressBar(self.centralwidget)
        self.translate_process_bar.setObjectName(u"translate_process_bar")
        self.translate_process_bar.setGeometry(QRect(10, 320, 691, 23))
        self.translate_process_bar.setCursor(QCursor(Qt.UpArrowCursor))
        self.translate_process_bar.setValue(9)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(216, 91, 71, 16))
        self.translator = QComboBox(self.centralwidget)
        self.translator.addItem("")
        self.translator.setObjectName(u"translator")
        self.translator.setGeometry(QRect(280, 90, 81, 22))
        self.radio_use_tts = QRadioButton(self.centralwidget)
        self.radio_use_tts.setObjectName(u"radio_use_tts")
        self.radio_use_tts.setGeometry(QRect(430, 70, 121, 19))
        self.radio_use_audio = QRadioButton(self.centralwidget)
        self.radio_use_audio.setObjectName(u"radio_use_audio")
        self.radio_use_audio.setGeometry(QRect(430, 190, 98, 19))
        self.select_audio_file_but = QPushButton(self.centralwidget)
        self.select_audio_file_but.setObjectName(u"select_audio_file_but")
        self.select_audio_file_but.setGeometry(QRect(430, 220, 91, 23))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(420, 90, 491, 81))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 54, 41, 16))
        self.role2 = QComboBox(self.frame)
        self.role2.addItem("")
        self.role2.addItem("")
        self.role2.addItem("")
        self.role2.addItem("")
        self.role2.setObjectName(u"role2")
        self.role2.setGeometry(QRect(240, 50, 151, 22))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 70, 371, 91))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 60, 111, 16))
        self.label_6.setFont(font3)
        self.speaknum_box = QComboBox(self.frame_2)
        self.speaknum_box.addItem("")
        self.speaknum_box.addItem("")
        self.speaknum_box.setObjectName(u"speaknum_box")
        self.speaknum_box.setGeometry(QRect(120, 60, 61, 22))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(420, 210, 491, 41))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.ref_audio_file_lab = QLabel(self.frame_3)
        self.ref_audio_file_lab.setObjectName(u"ref_audio_file_lab")
        self.ref_audio_file_lab.setGeometry(QRect(130, 10, 291, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.startbut.raise_()
        self.select_inputpath.raise_()
        self.select_savepath.raise_()
        self.inputpath_2.raise_()
        self.savepath.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.origin_lang.raise_()
        self.target_lang.raise_()
        self.label_3.raise_()
        self.role1.raise_()
        self.preview_role.raise_()
        self.translate_process_bar.raise_()
        self.label_4.raise_()
        self.translator.raise_()
        self.radio_use_tts.raise_()
        self.radio_use_audio.raise_()
        self.select_audio_file_but.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 928, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.startbut.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SynthereDub", None))
        self.startbut.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.select_inputpath.setText(QCoreApplication.translate("MainWindow", u"Select Video", None))
        self.select_savepath.setText(QCoreApplication.translate("MainWindow", u"SaveTo", None))
        self.inputpath_2.setText(QCoreApplication.translate("MainWindow", u"Your selected video ", None))
        self.savepath.setText(QCoreApplication.translate("MainWindow", u"Save the translated video and txt to", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Original language", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Translate to", None))
        self.origin_lang.setItemText(0, QCoreApplication.translate("MainWindow", u"EN", None))
        self.origin_lang.setItemText(1, QCoreApplication.translate("MainWindow", u"AutoDetect", None))

        self.target_lang.setItemText(0, QCoreApplication.translate("MainWindow", u"CN", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Role1", None))
        self.role1.setItemText(0, QCoreApplication.translate("MainWindow", u"zh-CN-YunxiNeural", None))
        self.role1.setItemText(1, QCoreApplication.translate("MainWindow", u"zh-CN-YunjianNeural", None))
        self.role1.setItemText(2, QCoreApplication.translate("MainWindow", u"zh-CN-XiaoxiaoNeural", None))
        self.role1.setItemText(3, QCoreApplication.translate("MainWindow", u"zh-CN-XiaoyiNeural", None))

        self.preview_role.setText(QCoreApplication.translate("MainWindow", u"Preview", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Translator", None))
        self.translator.setItemText(0, QCoreApplication.translate("MainWindow", u"microsoft", None))

        self.radio_use_tts.setText(QCoreApplication.translate("MainWindow", u"Use EDGE TTS", None))
        self.radio_use_audio.setText(QCoreApplication.translate("MainWindow", u"Use Audio", None))
        self.select_audio_file_but.setText(QCoreApplication.translate("MainWindow", u"Select Audio", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Role2", None))
        self.role2.setItemText(0, QCoreApplication.translate("MainWindow", u"zh-CN-YunjianNeural", None))
        self.role2.setItemText(1, QCoreApplication.translate("MainWindow", u"zh-CN-YunxiNeural", None))
        self.role2.setItemText(2, QCoreApplication.translate("MainWindow", u"zh-CN-XiaoxiaoNeural", None))
        self.role2.setItemText(3, QCoreApplication.translate("MainWindow", u"zh-CN-XiaoyiNeural", None))

        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Speaker Num", None))
        self.speaknum_box.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.speaknum_box.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))

        self.ref_audio_file_lab.setText(QCoreApplication.translate("MainWindow", u"Selected audio file", None))
    # retranslateUi

